### ISSUE TITLE
email.pl não está rodando

### ISSUE THREAD

**Issue by fsilveira060** [sansaoipb/Email-Graph-ZABBIX#1]
Eu uso Centos7, baixei todos os pacotes que foram solicitados e Aparece o seguinte erro quando eu tento testá-lo:
Can't locate JSON/RPC/Client.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/shar          e/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./email.pl line 30.
BEGIN failed--compilation aborted at ./email.pl line 30.

**Comment by sansaoipb** [comment]
Boa noite.
Ele está reclamando do modulo "JSON::RPC::Client". Ele não deve ter sido
instalado, verifique se ele realmente foi instalado.

yum install perl-JSON-RPC


*Eracydes Carvalho*


*Microsoft Certified Technology Specialist - ID: 923 222 9*
*ITIL® Foundation Certificate in IT Service Management - ID:
5208412.20337724**ZABBIX Certified Professional | **ZABBIX Certified
Specialist*



*Contatos*

*Tel: (21) 99200-5654 | LinkedIn <http://www.linkedin.com/in/sansaoipb>*

2016-10-08 18:18 GMT-03:00 Fernando Silveira Antunes Dias <
notifications@github.com>:
